### ISSUE TITLE
How to classify new sentences?

### ISSUE THREAD

**Issue by scottlingran** [linanqiu/word2vec-sentiments#2]
Is this possible with doc2vec?

``` python
newtext = "this move sucks"
# e.g. X = model.vectorize(newtext)
classifier.predict(X)
```

**Comment by linanqiu** [comment]
That's one of my personal peeves with doc2vec. As far as I know, you can't update the set. That's because each word and doc is a vector, and adding new corpus would change every word and doc's vectors. So it is not possible to do that without retraining the entire model then predicting it.

However gensim seems to have a hacky solution for that:

https://github.com/gojomo/gensim/blob/develop/gensim/models/doc2vec.py

Check out the infer_vector method

**Comment by scottlingran** [comment]
Yeah, that sucks :(

Just tried using `.infer_vector()` to re-score the classifier with the test set. The score drops from 87% to ~83%
